// GENERATED by scripts/build-challenges-manifest.ts — do not edit by hand.
// Derived from a real (near-)100% save: every gameplay challenge present, excluding
// platform achievements (Challenges.Achievements.*).
import type { CollectibleCounter } from "../collectibles.js";
export const CHALLENGES: CollectibleCounter[] = [
  {
    "key": "Challenges",
    "label": "Challenges",
    "counter": 41,
    "verified": false,
    "stateValue": "ETtChallengeGameProgressState::Rewarded",
    "tags": [
          {
                "tag": "GameProgress.Definitions.Challenges.9Lives",
                "name": "9 Lives (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Assassin",
                "name": "Assassin (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Bouncer",
                "name": "Bouncer (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Brawler",
                "name": "Brawler (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.BrutalCombat",
                "name": "Brutal Combat (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.BruteMan",
                "name": "Brute Man (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.BuddySystem",
                "name": "Buddy System (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Calculator",
                "name": "Calculator (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.CheckItOut",
                "name": "Check It Out (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Collector",
                "name": "Collector (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.ControlledBlast",
                "name": "Controlled Blast (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.CounterMeasures",
                "name": "Counter Measures (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Demolisher",
                "name": "Demolisher (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Dodgeball",
                "name": "Dodgeball (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.EveryonesACritic",
                "name": "Everyones A Critic (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.FallDamage",
                "name": "Fall Damage (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.FocusedFighter",
                "name": "Focused Fighter (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.HairTrigger",
                "name": "Hair Trigger (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Hazard",
                "name": "Hazard (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.HighVoltage",
                "name": "High Voltage (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.InBlackestNight",
                "name": "In Blackest Night (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Kiteman",
                "name": "Kiteman (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Ledgendary",
                "name": "Ledgendary (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.LivingDangerously",
                "name": "Living Dangerously (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.MultiMan",
                "name": "Multi Man (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Multitasker",
                "name": "Multitasker (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.ParanormalInvestigator",
                "name": "Paranormal Investigator (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.PiedPiper",
                "name": "Pied Piper (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Recycler",
                "name": "Recycler (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Samurai",
                "name": "Samurai (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.ShieldSurfer",
                "name": "Shield Surfer (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.SpeedySafecracker",
                "name": "Speedy Safecracker (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Teleporter",
                "name": "Teleporter (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.TheHighLife",
                "name": "The High Life (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Theatrical",
                "name": "Theatrical (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Theatrical.TriggerArea",
                "name": "Theatrical — Trigger Area (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.ToughGuy",
                "name": "Tough Guy (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.TreasureHunter",
                "name": "Treasure Hunter (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Turbo",
                "name": "Turbo (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Untouchable",
                "name": "Untouchable (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.Challenges.Whiplash",
                "name": "Whiplash (Challenge)",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          }
    ]
  }
];
