// GENERATED by scripts/build-purplestuds-manifest.ts — do not edit by hand.
// Tag universe extracted from the game's PROG_PurpleStuds definition asset
// (saves are sparse and can't list uncollected ones). Source: purplestuds.tags.json.
import type { CollectibleCounter } from "../collectibles.js";
export const PURPLE_STUDS: CollectibleCounter[] = [
  {
    "key": "PurpleStuds",
    "label": "Purple studs",
    "counter": 84,
    "verified": false,
    "stateValue": "EPurpleStudGameProgressState::Collected",
    "tags": [
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Batcave.Exploration.00PS",
                "name": "Batcave — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "other"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.GVRP.Exploration.PS.00PS",
                "name": "Gotham Village - Robinson Park — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Gotham Village - Robinson Park"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.GVRP.Exploration.PS.01PS",
                "name": "Gotham Village - Robinson Park — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Gotham Village - Robinson Park"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.GVRP.Exploration.PS.02PS",
                "name": "Gotham Village - Robinson Park — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Gotham Village - Robinson Park"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.GVRP.Exploration.PS.03PS",
                "name": "Gotham Village - Robinson Park — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Gotham Village - Robinson Park"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.NT01.Exploration.PS.00PS",
                "name": "Newtown — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Newtown"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.NT01.Exploration.PS.01PS",
                "name": "Newtown — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Newtown"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.NT01.Exploration.PS.02PS",
                "name": "Newtown — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Newtown"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.NT01.Exploration.PS.03PS",
                "name": "Newtown — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Newtown"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.CI.NT01.Exploration.PS.04PS",
                "name": "Newtown — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Central Island",
                      "district": "Newtown"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.NI.EEAM.Exploration.PS.00PS",
                "name": "East End - Amusement Mile — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "North Island",
                      "district": "East End - Amusement Mile"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.NI.EEAM.Exploration.PS.01PS",
                "name": "East End - Amusement Mile — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "North Island",
                      "district": "East End - Amusement Mile"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.NI.EEAM.Exploration.PS.02PS",
                "name": "East End - Amusement Mile — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "North Island",
                      "district": "East End - Amusement Mile"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.NI.EEAM.Exploration.PS.03PS",
                "name": "East End - Amusement Mile — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "North Island",
                      "district": "East End - Amusement Mile"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.NI.EEAM.Exploration.PS.04PS",
                "name": "East End - Amusement Mile — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "North Island",
                      "district": "East End - Amusement Mile"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.NI.EEAM.Exploration.PS.05PS",
                "name": "East End - Amusement Mile — Purple Stud #6",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "North Island",
                      "district": "East End - Amusement Mile"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.00PS",
                "name": "The Cauldron Central — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.01PS",
                "name": "The Cauldron Central — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.02PS",
                "name": "The Cauldron Central — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.03PS",
                "name": "The Cauldron Central — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.04PS",
                "name": "The Cauldron Central — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.05PS",
                "name": "The Cauldron Central — Purple Stud #6",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.06PS",
                "name": "The Cauldron Central — Purple Stud #7",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CA01.Exploration.PS.07PS",
                "name": "The Cauldron Central — Purple Stud #8",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron Central"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CAAC.Exploration.PS.00PS",
                "name": "The Cauldron North - ACE Chemicals — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron North - ACE Chemicals"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CAAC.Exploration.PS.01PS",
                "name": "The Cauldron North - ACE Chemicals — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron North - ACE Chemicals"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CAAC.Exploration.PS.02PS",
                "name": "The Cauldron North - ACE Chemicals — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron North - ACE Chemicals"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.CAAC.Exploration.PS.03PS",
                "name": "The Cauldron North - ACE Chemicals — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "The Cauldron North - ACE Chemicals"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG01.Exploration.PS.00PS",
                "name": "Old Gotham North — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham North"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG01.Exploration.PS.01PS",
                "name": "Old Gotham North — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham North"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG01.Exploration.PS.02PS",
                "name": "Old Gotham North — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham North"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG01.Exploration.PS.03PS",
                "name": "Old Gotham North — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham North"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG01.Exploration.PS.04PS",
                "name": "Old Gotham North — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham North"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG02.Exploration.PS.00PS",
                "name": "Old Gotham South — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham South"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG02.Exploration.PS.01PS",
                "name": "Old Gotham South — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham South"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG02.Exploration.PS.02PS",
                "name": "Old Gotham South — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham South"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG02.Exploration.PS.03PS",
                "name": "Old Gotham South — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham South"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG02.Exploration.PS.04PS",
                "name": "Old Gotham South — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham South"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG03.Exploration.PS.00PS",
                "name": "Old Gotham West — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham West"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG03.Exploration.PS.01PS",
                "name": "Old Gotham West — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham West"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG03.Exploration.PS.02PS",
                "name": "Old Gotham West — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham West"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG03.Exploration.PS.03PS",
                "name": "Old Gotham West — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham West"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG03.Exploration.PS.04PS",
                "name": "Old Gotham West — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham West"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.SI.OG03.Exploration.PS.05PS",
                "name": "Old Gotham West — Purple Stud #6",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "South Island",
                      "district": "Old Gotham West"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.00PS",
                "name": "Tricorner — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.01PS",
                "name": "Tricorner — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.02PS",
                "name": "Tricorner — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.03PS",
                "name": "Tricorner — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.04PS",
                "name": "Tricorner — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.05PS",
                "name": "Tricorner — Purple Stud #6",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Hub.TC.TC01.Exploration.PS.06PS",
                "name": "Tricorner — Purple Stud #7",
                "confidence": "high",
                "facets": {
                      "source": "hub",
                      "island": "Tri-Corner",
                      "district": "Tricorner"
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.03.01PS",
                "name": "Story 0-3 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 3
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.03.02PS",
                "name": "Story 0-3 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 3
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.03.03PS",
                "name": "Story 0-3 — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 3
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.04.01PS",
                "name": "Story 0-4 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 4
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.04.02PS",
                "name": "Story 0-4 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 4
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.04.04PS",
                "name": "Story 0-4 — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 4
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.00.04.05PS",
                "name": "Story 0-4 — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 0,
                      "mission": 4
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.01.01PS",
                "name": "Story 1-1 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 1
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.01.02PS",
                "name": "Story 1-1 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 1
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.05.01PS",
                "name": "Story 1-5 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 5
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.02PS",
                "name": "Story 1-9 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.03PS",
                "name": "Story 1-9 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.04PS",
                "name": "Story 1-9 — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.05PS",
                "name": "Story 1-9 — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.06PS",
                "name": "Story 1-9 — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.07PS",
                "name": "Story 1-9 — Purple Stud #6",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.01.09.08PS",
                "name": "Story 1-9 — Purple Stud #7",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 1,
                      "mission": 9
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.02.03.01PS",
                "name": "Story 2-3 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 2,
                      "mission": 3
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.02.03.02PS",
                "name": "Story 2-3 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 2,
                      "mission": 3
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.02.05.01PS",
                "name": "Story 2-5 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 2,
                      "mission": 5
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.02.08.01PS",
                "name": "Story 2-8 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 2,
                      "mission": 8
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.03.02.01PS",
                "name": "Story 3-2 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 3,
                      "mission": 2
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.03.06.01PS",
                "name": "Story 3-6 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 3,
                      "mission": 6
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.03.06.02PS",
                "name": "Story 3-6 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 3,
                      "mission": 6
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.03.06.03PS",
                "name": "Story 3-6 — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 3,
                      "mission": 6
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.04.02.01PS",
                "name": "Story 4-2 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 4,
                      "mission": 2
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.04.02.02PS",
                "name": "Story 4-2 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 4,
                      "mission": 2
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.04.02.03PS",
                "name": "Story 4-2 — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 4,
                      "mission": 2
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.06.01.01PS",
                "name": "Story 6-1 — Purple Stud #1",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 6,
                      "mission": 1
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.06.01.02PS",
                "name": "Story 6-1 — Purple Stud #2",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 6,
                      "mission": 1
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.06.01.03PS",
                "name": "Story 6-1 — Purple Stud #3",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 6,
                      "mission": 1
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.06.01.04PS",
                "name": "Story 6-1 — Purple Stud #4",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 6,
                      "mission": 1
                }
          },
          {
                "tag": "GameProgress.Definitions.PurpleStuds.Story.06.01.05PS",
                "name": "Story 6-1 — Purple Stud #5",
                "confidence": "high",
                "facets": {
                      "source": "story",
                      "chapter": 6,
                      "mission": 1
                }
          }
    ]
  }
];
