import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PROGRESS_MISSION_TAGS, PROGRESS_OBJECTIVE_TAGS } from "../src/data/progress.generated.js";
import { COLLECTIBLES } from "../src/data/collectibles.generated.js";
import { DISTRICTS } from "../src/data/collectibles-mapping.js";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const stObj: [string, string][] = JSON.parse(readFileSync(here("../src/data/st-objective.json"), "utf8"));
const progNames: Record<string, string> = JSON.parse(readFileSync(here("../src/data/prog-mission-names.json"), "utf8"));
const OUT = here("../src/data/progress-names.generated.ts");

// Friendly labels for activity types (the segment after the district in Activities tags).
const ACTIVITY: Record<string, string> = {
  Croc: "Killer Croc", Heist: "Heist", Zoo: "Zoo Animal", Photofit: "Photofit (Wanted)",
  Plant: "Poison Ivy Plant", Riddler: "Riddler", Cluemaster: "Cluemaster", Puzzle: "Puzzle",
  FastTravel: "SubWayne Station", UpgradeArea: "Upgrade Area", Combat: "Combat Trial",
  Traversal: "Traversal Trial", ARChallenges: "AR Challenge", RandomCrimes: "Random Crime",
};

// Story mission names ("Iceberg Lounge (Ch.1 M5)") from the collectibles manifest.
const storyMission = new Map<string, string>();
for (const c of COLLECTIBLES)
  for (const t of c.tags) {
    if (t.facets.source !== "story") continue;
    const key = `${t.facets.chapter}.${t.facets.mission}`;
    const prefix = t.name.split(" — ")[0]!;
    if (/\(Ch\./.test(prefix) && !storyMission.has(key)) storyMission.set(key, prefix);
  }

// Index ST_Objective: numbered keys by chapter.mission.nn, named keys by chapter.mission (in file order).
const numIdx = new Map<string, string>();
const namedByMission = new Map<string, string[]>();
for (const [k, v] of stObj) {
  const m = k.match(/^OBJ_C(\d+)M(\d+)[A-Z]?_OBJ(\d+)$/);
  if (m) {
    const key = `${+m[1]!}.${+m[2]!}.${+m[3]!}`;
    if (!numIdx.has(key)) numIdx.set(key, v); // first variant wins
  } else {
    const m2 = k.match(/^OBJ_C(\d+)M(\d+)[A-Z]?_(.+)$/);
    if (m2) {
      const key = `${+m2[1]!}.${+m2[2]!}`;
      (namedByMission.get(key) ?? namedByMission.set(key, []).get(key)!).push(v);
    }
  }
}

// Group our story objective tags by mission, sorted, for order-matching named-key missions.
const objKey = (t: string) => {
  const m = t.match(/\.Story\.(\d+)\.(\d+)\.OBJ(\d+)(?:\.([A-Z]))?/);
  return m ? { mk: `${+m[1]!}.${+m[2]!}`, nn: +m[3]!, sub: m[4] ?? "", num: `${+m[1]!}.${+m[2]!}.${+m[3]!}` } : null;
};
const storyObjByMission = new Map<string, string[]>();
for (const t of PROGRESS_OBJECTIVE_TAGS) {
  const k = objKey(t);
  if (k) (storyObjByMission.get(k.mk) ?? storyObjByMission.set(k.mk, []).get(k.mk)!).push(t);
}
for (const list of storyObjByMission.values())
  list.sort((a, b) => {
    const ka = objKey(a)!, kb = objKey(b)!;
    return ka.nn - kb.nn || ka.sub.localeCompare(kb.sub);
  });

const names: Record<string, string> = {};
const actName = (island: string, dist: string, type: string) => {
  void island;
  return `${ACTIVITY[type] ?? type.replace(/([a-z])([A-Z])/g, "$1 $2")}${DISTRICTS[dist] ? ` — ${DISTRICTS[dist]}` : ""}`;
};

// ── Objectives ──
let exact = 0, ordered = 0;
for (const t of PROGRESS_OBJECTIVE_TAGS) {
  const k = objKey(t);
  if (k) {
    const direct = numIdx.get(k.num);
    if (direct) {
      names[t] = k.sub ? `${direct} (part ${k.sub})` : direct;
      exact++;
      continue;
    }
    const tags = storyObjByMission.get(k.mk);
    const named = namedByMission.get(k.mk);
    if (tags && named && tags.length === named.length) {
      const i = tags.indexOf(t);
      if (i >= 0) { names[t] = named[i]!; ordered++; continue; }
    }
  }
  // (activity / other objectives fall back to a prettified path in the UI)
}

// ── Missions ──
let storyM = 0, actM = 0;
for (const t of PROGRESS_MISSION_TAGS) {
  const sm = t.match(/\.Story\.(\d+)\.(\d+)$/);
  if (sm) {
    const k = `${+sm[1]!}.${+sm[2]!}`;
    const n = progNames[k] ?? storyMission.get(k);
    if (n) { names[t] = n; storyM++; }
    continue;
  }
  const am = t.match(/\.Activities\.Instances\.([A-Z]+)\.([A-Z0-9]+)\.([A-Za-z]+)/);
  if (am) { names[t] = actName(am[1]!, am[2]!, am[3]!); actM++; }
}

writeFileSync(
  OUT,
  "// GENERATED by scripts/build-progress-names.ts — do not edit by hand.\n" +
    "// Natural-language names for mission/objective tags, from the game's ST_Objective string table\n" +
    "// + derived district/activity names. Tags not present here fall back to a prettified path in the UI.\n" +
    `export const PROGRESS_NAMES: Record<string, string> = ${JSON.stringify(names, null, 0)};\n`,
);
console.log(`objectives: ${exact} exact-text + ${ordered} order-matched = ${exact + ordered} named`);
console.log(`missions: ${storyM} story + ${actM} activity = ${storyM + actM} named`);
console.log(`total tags named: ${Object.keys(names).length} (rest fall back to prettified path)`);
