/**
 * Build the Purple Studs catalogue.
 *
 * Purple studs live in the same flat SavedGameProgressEnumValues array as
 * collectibles (tag + EPurpleStudGameProgressState), so once catalogued they use
 * the identical insert/complete machinery. They CAN'T be derived from a save the
 * way other counters are — saves are sparse, so an uncollected purple stud leaves
 * no entry. Even a "100%" save we had held only 38 of the 84.
 *
 * So the tag universe is extracted from the game's own definition asset and
 * committed as src/data/purplestuds.tags.json. To refresh it (e.g. after a patch),
 * with the game files mounted:
 *
 *   retoc to-legacy --version UE5_6 --no-shaders -f PurpleStud "<Paks>" <out>
 *   strings -n3 <out>/.../GameProgress/PROG_PurpleStuds.uasset \
 *     | grep -E '^GameProgress\.Definitions\.PurpleStuds\.' | grep -E '[0-9]{2}PS$' \
 *     | grep -viE 'TestLevel|UserTest' | sort -u > src/data/purplestuds.tags.json (as a JSON array)
 *
 * Run: pnpm -C packages/core exec tsx scripts/build-purplestuds-manifest.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ISLANDS, DISTRICTS } from "../src/data/collectibles-mapping.js";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const tags: string[] = JSON.parse(readFileSync(here("../src/data/purplestuds.tags.json"), "utf8"));

type Facets = { source: "story" | "hub" | "other"; chapter?: number; mission?: number; island?: string; district?: string };

/** Per-location running index so names read "Old Gotham South — Purple Stud #1, #2…". */
const seen = new Map<string, number>();
const nextIdx = (key: string) => {
  const n = (seen.get(key) ?? 0) + 1;
  seen.set(key, n);
  return n;
};

function describe(tag: string): { name: string; facets: Facets } {
  const rest = tag.replace(/^GameProgress\.Definitions\.PurpleStuds\./, "");
  const hub = rest.match(/^Hub\.([A-Z]+)\.([A-Za-z0-9]+)\./);
  if (hub) {
    const island = ISLANDS[hub[1]!] ?? hub[1]!;
    const district = DISTRICTS[hub[2]!] ?? hub[2]!;
    const i = nextIdx(`hub:${district}`);
    return { name: `${district} — Purple Stud #${i}`, facets: { source: "hub", island, district } };
  }
  const story = rest.match(/^Story\.(\d+)\.(\d+)\./);
  if (story) {
    const chapter = Number(story[1]);
    const mission = Number(story[2]);
    const i = nextIdx(`story:${chapter}.${mission}`);
    return { name: `Story ${chapter}-${mission} — Purple Stud #${i}`, facets: { source: "story", chapter, mission } };
  }
  const i = nextIdx("batcave");
  return { name: `Batcave — Purple Stud #${i}`, facets: { source: "other" } };
}

const entries = tags.sort().map((tag) => {
  const { name, facets } = describe(tag);
  return { tag, name, confidence: "high" as const, facets };
});

const out = `// GENERATED by scripts/build-purplestuds-manifest.ts — do not edit by hand.
// Tag universe extracted from the game's PROG_PurpleStuds definition asset
// (saves are sparse and can't list uncollected ones). Source: purplestuds.tags.json.
import type { CollectibleCounter } from "../collectibles.js";
export const PURPLE_STUDS: CollectibleCounter[] = [
  {
    "key": "PurpleStuds",
    "label": "Purple studs",
    "counter": ${entries.length},
    "verified": false,
    "stateValue": "EPurpleStudGameProgressState::Collected",
    "tags": ${JSON.stringify(entries, null, 6).replace(/\n/g, "\n    ")}
  }
];
`;

writeFileSync(here("../src/data/purplestuds.generated.ts"), out);
console.log(`Wrote ${entries.length} purple stud tags to src/data/purplestuds.generated.ts`);
