/**
 * Build the Challenges catalogue from a real (near-)100% save fixture.
 *
 * Challenges live in the same flat SavedGameProgressEnumValues array as
 * collectibles (tag + ETtChallengeGameProgressState), so they use the identical
 * insert mechanism — they just weren't catalogued. We derive the gameplay
 * challenge tag universe from a maxed save (every challenge present, state
 * "Rewarded") and emit it as a CollectibleCounter so the existing unlock /
 * completion / panel machinery picks them up.
 *
 * The platform Achievements (Challenges.Achievements.*) are intentionally
 * excluded — they're meta, not part of in-game completion.
 *
 * Run: pnpm -C packages/core exec tsx scripts/build-challenges-manifest.ts
 * (requires test/fixtures/slot0_thirdparty_100pct.sav locally; gitignored)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SaveFile } from "../src/sav/index.js";

const fixture = fileURLToPath(new URL("../test/fixtures/slot0_thirdparty_100pct.sav", import.meta.url));
if (!existsSync(fixture)) {
  console.error("Missing fixture test/fixtures/slot0_thirdparty_100pct.sav — cannot rebuild challenges manifest.");
  process.exit(1);
}

const save = SaveFile.load(new Uint8Array(readFileSync(fixture)));
const tags = save
  .enumArrayEntries()
  .map((e) => e.tag)
  .filter((t) => /^GameProgress\.Definitions\.Challenges\./.test(t) && !/\.Achievements\./.test(t))
  .sort();

const prettify = (t: string) =>
  t
    .replace(/^GameProgress\.Definitions\.Challenges\./, "")
    .replace(/\./g, " — ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .trim();

const entries = tags.map((tag) => ({
  tag,
  name: `${prettify(tag)} (Challenge)`,
  confidence: "high" as const,
  facets: { source: "other" as const },
}));

const out = `// GENERATED by scripts/build-challenges-manifest.ts — do not edit by hand.
// Derived from a real (near-)100% save: every gameplay challenge present, excluding
// platform achievements (Challenges.Achievements.*).
import type { CollectibleCounter } from "../collectibles.js";
export const CHALLENGES: CollectibleCounter[] = [
  {
    "key": "Challenges",
    "label": "Challenges",
    "counter": ${entries.length},
    "verified": false,
    "stateValue": "ETtChallengeGameProgressState::Rewarded",
    "tags": ${JSON.stringify(entries, null, 6).replace(/\n/g, "\n    ")}
  }
];
`;

const dest = fileURLToPath(new URL("../src/data/challenges.generated.ts", import.meta.url));
writeFileSync(dest, out);
console.log(`Wrote ${entries.length} challenge tags to src/data/challenges.generated.ts`);
