import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { decrypt } from "../src/crypt/index.js";
import { parse } from "../src/gvas/index.js";
import { readEnumArrayEntries } from "../src/gvas/scan.js";
import { normalizeConfidence, prettifyTagPath, deriveFacets, selectCounterTags } from "../src/collectibles.js";
import { COUNTER_MAPPINGS } from "../src/data/collectibles-mapping.js";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const SAVE = here("../test/fixtures/slot0_thirdparty_100pct.sav");
const NAMES = here("../src/data/collectible-names.json");
const OUT = here("../src/data/collectibles.generated.ts");

const body = parse(decrypt(new Uint8Array(readFileSync(SAVE)))).body;
const entries = readEnumArrayEntries(body);
const universe = entries.map((e) => e.tag);
const names: Record<string, { name: string; confidence: string }> = JSON.parse(readFileSync(NAMES, "utf8"));

/** Most common state among a category's tags = the "collected" value to write on insert. */
function canonicalState(category: string): string {
  const counts = new Map<string, number>();
  for (const e of entries) {
    if (e.tag.startsWith(`GameProgress.Definitions.${category}.`)) {
      counts.set(e.state, (counts.get(e.state) ?? 0) + 1);
    }
  }
  let best = "";
  let n = -1;
  for (const [s, c] of counts) if (c > n) ((best = s), (n = c));
  if (!best) throw new Error(`No state found for category ${category}`);
  return best;
}

const out = COUNTER_MAPPINGS.map((m) => {
  const tags = selectCounterTags(universe, m);
  if (tags.length !== m.counter) {
    throw new Error(`Counter ${m.key}: selected ${tags.length} tags but expected ${m.counter}`);
  }
  return {
    key: m.key,
    label: m.label,
    counter: m.counter,
    verified: m.verified,
    stateValue: canonicalState(m.stateCategory),
    tags: tags.map((t) => ({
      tag: t,
      name: names[t]?.name ?? prettifyTagPath(t),
      confidence: normalizeConfidence(names[t]?.confidence ?? "low"),
      facets: deriveFacets(t),
    })),
  };
});

// global dedup check across counters
const seen = new Set<string>();
for (const c of out) for (const t of c.tags) {
  if (seen.has(t.tag)) throw new Error(`duplicate tag across counters: ${t.tag}`);
  seen.add(t.tag);
}

const file =
  "// GENERATED by scripts/build-collectibles-manifest.ts — do not edit by hand.\n" +
  'import type { CollectibleCounter } from "../collectibles.js";\n' +
  `export const COLLECTIBLES: CollectibleCounter[] = ${JSON.stringify(out, null, 2)};\n`;
writeFileSync(OUT, file);
console.log(
  `Wrote ${out.length} counters, ${out.reduce((a, c) => a + c.tags.length, 0)} tags -> collectibles.generated.ts`,
);
for (const c of out) console.log(`  ${c.key.padEnd(16)} ${String(c.counter).padStart(4)}  state=${c.stateValue}`);
