import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { decrypt } from "../src/crypt/index.js";
import { parse } from "../src/gvas/index.js";
import { readEnumArrayEntries } from "../src/gvas/scan.js";

// The full universe of mission + objective entries, from the 100% save, so the
// editor can show every mission/objective (not just the ones in the loaded save)
// and add+complete the missing ones. Names are derived in the UI.
const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const SAVE = here("../test/fixtures/slot0_thirdparty_100pct.sav");
const OUT = here("../src/data/progress.generated.ts");

const MISSION_ENUM = "ETtMissionGameProgress::";
const OBJECTIVE_ENUM = "ETtObjectivesNodeGameProgress::";

const entries = readEnumArrayEntries(parse(decrypt(new Uint8Array(readFileSync(SAVE)))).body);
const missionTags = [...new Set(entries.filter((e) => e.state.startsWith(MISSION_ENUM)).map((e) => e.tag))].sort();
const objectiveTags = [...new Set(entries.filter((e) => e.state.startsWith(OBJECTIVE_ENUM)).map((e) => e.tag))].sort();

const file =
  "// GENERATED by scripts/build-progress-manifest.ts — do not edit by hand.\n" +
  "// Full universe of mission + objective gameplay tags (from the 100% save).\n" +
  `export const PROGRESS_MISSION_TAGS: string[] = ${JSON.stringify(missionTags, null, 0)};\n` +
  `export const PROGRESS_OBJECTIVE_TAGS: string[] = ${JSON.stringify(objectiveTags, null, 0)};\n` +
  '/** State written when adding a missing mission/objective as done. */\n' +
  'export const MISSION_COMPLETE_STATE = "ETtMissionGameProgress::Complete";\n' +
  'export const OBJECTIVE_COMPLETE_STATE = "ETtObjectivesNodeGameProgress::Complete";\n';
writeFileSync(OUT, file);
console.log(`Wrote ${missionTags.length} mission tags + ${objectiveTags.length} objective tags -> progress.generated.ts`);
